Use python for ENV extraction
steelbrain/consistent-env pull request #39
Opened 2017-05-26 16:09 UTC by steelbrain

We still fallback to `env` when python is not available

2017-05-26 16:22 UTC, Unrud commented on src/helpers.js
> +  stdin.push(shellScript)
This doesn't work. The shell script is not compatible with many shells (like **fish** or **csh**).

2017-05-26 16:23 UTC, steelbrain commented on src/helpers.js
> +  stdin.push(shellScript)
Thanks for the heads up, I'll test this manually in csh and fish to confirm!

2017-05-26 16:25 UTC, Unrud commented on src/helpers.js
> +  const pythonFile = Path.join(Path.dirname(__dirname), 'index.py')
Just run something like ``python -c 'import os;print("\0".join(map("=".join, dict(os.environ).items())))'``, no need to create a file.

2017-05-26 16:25 UTC, Arcanemagus requested changes
I very much prefer the pure shell method in #38 instead of bringing in a dependency on `python`.

2017-05-26 16:25 UTC, Arcanemagus commented on src/helpers.js
> +  return contents.split(contents.includes('\0') ? '\0' : '\n')
The entire problem is that the previous code was splitting on `\n`, What reason could there be for keeping that broken behavior?

2017-05-26 16:25 UTC, Arcanemagus commented on src/helpers.js
> +  const pythonFile = Path.join(Path.dirname(__dirname), 'index.py')
Just do `__dirname, '..'`, no sense in doing this silly "dirname of a dirname" code.

2017-05-26 16:27 UTC, steelbrain commented on src/helpers.js
> +  const pythonFile = Path.join(Path.dirname(__dirname), 'index.py')
Removed in latest push

2017-05-26 16:28 UTC, steelbrain commented on src/helpers.js
> +  return contents.split(contents.includes('\0') ? '\0' : '\n')
We are using python splitting when it's available but when it's not we fallback to env, and we still need to split the env output with `\n`

2017-05-26 16:30 UTC, steelbrain commented
@Arcanemagus Python is available in all linux distros that I'm aware of and macOS by default. That's why we're using it, even if it doesn't, we still fallback to the `env` way.

The main concern I had with the pure shell method was that it was still getting splitting the output by `\n`, it was just using some regexp to validate, this solution is rock-solid

I am open to suggestions tho :)

2017-05-26 16:33 UTC, Unrud commented on src/helpers.js
> +  stdin.push(shellScript)
You can wrap the script in sh, as I did in #36 for incompatible shells.

2017-05-26 16:34 UTC, Unrud commented on src/helpers.js
> +      env
I would remove this. If you really need a fallback, use something like the script from #36.

2017-05-26 16:35 UTC, steelbrain commented
@Unrud This was a PoC PR. I will have some time to finish this tonight, but if you want to open a new PR with similar functionality, that would be 👍

2017-05-26 18:25 UTC, Unrud commented
> The main concern I had with the pure shell method was that it was still getting splitting the output by ``\n``.

It only does this to find potential names of environment variables. It does further checks to validate that the name is real and it uses a safe method to retrieve the contents of environment variable.

> PR with similar functionality

#40

2017-05-27 16:49 UTC, steelbrain commented
Closing in favor of #40

2017-05-27 16:49 UTC, closed without merging